config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'about#index'

  get 'contact' => 'contact#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'

  devise_for :users
  resources :tickets
  resources :users
  resources :searches

  get '/tickets/search/:q', to: 'tickets#search', as: :simple_search

  root 'tickets#index'
end

app/models/about.rb
class About < ApplicationRecord
  has_attached_file :image
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\z}
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tickets
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
end

app/models/search.rb
class Search < ApplicationRecord
  def search_tickets
    tickets = Ticket.all

    tickets = tickets.where(['name LIKE ?', "%#{keywords}%"]) if keywords.present?
    tickets = tickets.where(['category_id LIKE ?', category]) if category.present?
    tickets = tickets.where(['price >= ?', min_price]) if min_price.present?
    tickets = tickets.where(['price <= ?', max_price]) if max_price.present?

    return tickets
  end
end

app/models/ticket.rb
# rubocop:disable LineLength
class Ticket < ApplicationRecord
  searchkick
  validates :name, :image, :code, :price, :stock_quantity, presence: true
  belongs_to :user
  belongs_to :category

  has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150>' }, default_url: '/system/tickets/images/missing.png'
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\z}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tickets
  belongs_to :province
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about = About.first
  end
end

app/controllers/application_controller.rb
# rubocop:disable LineLength
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :account_update, if: :devise_controller?

  def account_update
    @provinces = Province.all
  end

  def after_sign_in_path_for(_resource)
    current_user
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |user| user.permit(:first_name, :last_name, :province_id, :city, :email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |user| user.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |user| user.permit(:first_name, :last_name, :province_id, :address, :city, :country, :postal_code, :email, :password, :current_password, :remember_me) }
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.first
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
    @categories = Category.all.order('name')
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private

  def search_params
    params.require(:search).permit(:keywords, :category, :min_price, :max_price)
  end
end

app/controllers/tickets_controller.rb
# rubocop:disable LineLength
class TicketsController < ApplicationController
  before_action :find_ticket, only: %i(show edit update destroy)
  before_action :authenticate_user!, except: %i(index show search)

  def search
    @tickets = if params[:simple_search].present?
                 Ticket.search(params[:simple_search])
               else
                 Ticket.all
               end
  end

  def index
    @tickets = Ticket.all.order('name').page(params[:page]).per(5)
  end

  def show() end

  def new
    @ticket = current_user.tickets.build
    @categories = Category.all
  end

  def create
    @ticket = current_user.tickets.build(ticket_params)

    if @ticket.save
      redirect_to @ticket
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render 'edit'
    end
  end

  def destroy
    @ticket.destroy
    redirect_to root_path
  end

  private

  def find_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :description, :image, :code, :price, :stock_quantity, :status, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_tickets = @user.tickets
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    @user.first_name + ' ' + @user.last_name
  end
end

app/views/about/index.html.haml
%div.row.about
  %h2= @about.page_title
  %p= @about.content
  = image_tag @about.image

app/views/contact/index.html.haml
%h2= @contact.page_title
%p= @contact.content
%iframe{:src => "#{@contact.map}", :frameborder => "0", width: "100%", height: "350px"}

%p 
%strong Address: 
=@contact.address

%p 
%strong Postal Code: 
=@contact.postal_code

%p 
%strong City: 
=@contact.city

%p 
%strong Province: 
=@contact.province

%p 
%strong Country: 
=@contact.country

%p 
%strong Phone: 
=@contact.phone

%p 
%strong Email: 
=@contact.email

%p
  %a{:href => "#{@contact.facebook}"} face
  %a{:href => "#{@contact.twitter}"} twitter

app/views/searches/new.html.haml
%div.row
  %div.col-md-6
    = simple_form_for @search, html: { class: 'form-horizontal'} do |f|
      = f.input 	:keywords
      = f.input   :category, collection: @categories, label_method: :name, value_method: :id, include_blank: true
      = f.input  	:min_price
      = f.input  	:max_price
      = f.submit

app/views/searches/show.html.haml
%h1 Search Result
- if @search.search_tickets.empty?
  %p No tickets found
- else
  - @search.search_tickets.each do |ticket|
    %h2= link_to ticket.name, ticket
    %p= ticket.description

app/views/tickets/_ticketform.html.haml
%div.row
  %div.col-md-6
    = simple_form_for @ticket, html: { class: 'form-horizontal', multipart: true } do |f|
      = f.input 	:name, placeholder: 'Ticket name'
      = f.input :category_id, collection: @categories, label_method: :name, value_method: :id,label: "Category", include_blank: false, selected: @ticket.category_id
      = f.input 	:description, as: :text
      = f.input 	:image, as: :file
      = f.input   :code
      = f.input  	:price
      = f.input  	:stock_quantity
      = f.input   :status
      = f.submit

app/views/tickets/edit.html.haml
%h1 Edit Ticket

= render 'ticketform'

= link_to 'Cancel', ticket_path

app/views/tickets/index.html.haml
%div.row
  - @tickets.each do |ticket|
    %div.col-md-4
      %h2= link_to ticket.name, ticket
      %p= 	ticket.description
  
  %div.col-md-12  
    = paginate @tickets

app/views/tickets/new.html.haml
%h1 New Ticket

= render 'ticketform'

app/views/tickets/search.html.haml
- @tickets.each do |ticket|
  %h2= link_to ticket.name, ticket
  %p= 	ticket.description

app/views/tickets/show.html.haml
%article.row
  %div.md-col-4
    %h1= @ticket.name
    - if @ticket.category.present?
      %p= @ticket.category.name
    - else
      %p no category
    %p= @ticket.description
    = image_tag @ticket.image.url(:medium)
    %p= @ticket.code
    %p= number_to_currency(@ticket.price)
    %p= @ticket.stock_quantity
    %p= @ticket.status
    
    %p 
      Seller 
      = @ticket.user.email
    - if current_user != NIL && current_user.id == @ticket.user.id
      = link_to 'Edit', edit_ticket_path(@ticket)
      = link_to 'Delete', ticket_path(@ticket), method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/show.html.haml
%h1= full_name
%p= @user.email
%p= @user.address
%p= @user.province.name
%p= @user.city
%p= @user.country
%p= @user.postal_code

- @user_tickets.each do |ticket|
  %h2= link_to ticket.name, ticket
  %p= 	ticket.description