config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'about#index'

  get 'contact' => 'contact#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'

  devise_for :users
  resources :tickets
  resources :users
  resources :searches

  get '/tickets/search/:q', to: 'tickets#search', as: :simple_search

  root 'tickets#index'
end

app/models/about.rb
class About < ApplicationRecord
  has_attached_file :image
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\z}
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tickets
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
end

app/models/search.rb
class Search < ApplicationRecord
  def search_tickets
    tickets = Ticket.all

    tickets = tickets.where(['name LIKE ?', "%#{keywords}%"]) if keywords.present?
    tickets = tickets.where(['category_id LIKE ?', category]) if category.present?
    tickets = tickets.where(['price >= ?', min_price]) if min_price.present?
    tickets = tickets.where(['price <= ?', max_price]) if max_price.present?

    return tickets
  end
end

app/models/ticket.rb
# rubocop:disable LineLength
class Ticket < ApplicationRecord
  searchkick
  validates :name, :image, :code, :price, :stock_quantity, presence: true
  belongs_to :user
  belongs_to :category

  has_attached_file :image, styles: { large: '600x600>', medium: '300x300>', thumb: '150x150>' }, default_url: '/system/tickets/images/missing.png'
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\z}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tickets
  belongs_to :province
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about = About.first
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.first
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
    @categories = Category.all.order('name')
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private

  def search_params
    params.require(:search).permit(:keywords, :category, :min_price, :max_price)
  end
end

app/controllers/tickets_controller.rb
# rubocop:disable LineLength
class TicketsController < ApplicationController
  before_action :find_ticket, only: %i(show edit update destroy)
  before_action :authenticate_user!, except: %i(index show search)

  def search
    @tickets = if params[:simple_search].present?
                 Ticket.search(params[:simple_search])
               else
                 Ticket.all
               end
  end

  def index
    @tickets = Ticket.all.order('name').page(params[:page]).per(5)
  end

  def show() end

  def new
    @ticket = current_user.tickets.build
    @categories = Category.all
  end

  def create
    @ticket = current_user.tickets.build(ticket_params)

    if @ticket.save
      redirect_to @ticket
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render 'edit'
    end
  end

  def destroy
    @ticket.destroy
    redirect_to root_path
  end

  private

  def find_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :description, :image, :code, :price, :stock_quantity, :status, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_tickets = @user.tickets
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    @user.first_name + ' ' + @user.last_name
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Social Hub
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %div.container
      %header
        #logo
          %p Social Hub
        %div.row
          %div.col-md-6
            #buttons
              = link_to 'Home', root_path
              = link_to 'About', about_path
              = link_to 'Contact', contact_path
              - if user_signed_in?
                = link_to 'New Ticket', new_ticket_path
                = link_to 'My profile', current_user
                = link_to 'Edit profile', edit_user_registration_path
                = link_to 'Logout', destroy_user_session_path, method: :delete
              - else
                = link_to 'Sign Up', new_user_registration_path
                = link_to 'Sing In', new_user_session_path

          %div.col-md-6
            =simple_form_for :simple_search, html: { class: 'form-inline' }, url: search_path(:simple_search), :method => :get  do |f|
              =f.input :q, label: false, required: false, placeholder: 'Search'
              =f.submit "Search"
          = link_to 'Advanced Search', new_search_path

    %div.container
      %p.notice= notice
      %p.alert= alert

    %section.container
      = yield